spring.application.name=tours

spring.datasource.url=jdbc:postgresql://localhost:5432/guidedTourService
spring.datasource.username=postgres
spring.datasource.password=19dec1972Edik
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true